= 如何向 Jcohy Gradle Plugins 贡献代码

Jcohy Gradle Plugins 是在 Apache 2.0 许可证下发布。如果你想贡献一些东西，或者只是想修改代码，这个文档应该可以帮助到你。

== 行为准则

该项目的贡献者需要遵守以下行为准则: link:CODE_OF_CONDUCT.adoc[code of conduct].
如果有特殊情况，请将特殊的情况报告给 jia_chao23@126.com.

== 使用 GitHub Issues

我们使用 GitHub Issues 来对问题进行跟踪和改进。如果您要报告问题，或者有新的建议或意见，请在 https://github.com/jcohy/jcohy-gradle-plugins/issues[Github Issues] 上汇报问题。

关于新增功能或增强功能，请详细描述您的意向，以便我们能更好的理解您的想法。

如果您发现了一些 Bug，请尽可能的提供更多的关于问题的详细信息，最好能可以提供一个可以重现问题的小 Demo。

== 如何贡献代码

=== 讨论

如果你认为存在一个问题，通过一些不同的方法来搜索现有的 https://github.com/jcohy/jcohy-gradle-plugins/issues[issues]，找到过去或现在与该问题相关的讨论。阅读这些讨论可以帮助你了解这个问题，并帮助我们做出决定。

=== 创建一个 Issues

报告问题或提出功能请求是一种很好的贡献方式。您的反馈和由此产生的讨论会为我们提供源源不断的想法。但是，在创建正式的 ticket 之前，让我们先花些时间讨论和研究。

待一切准备好后，可以在 Github 上创建一个 issue

=== Issue 生命周期

首次创建 issue 时，它会自动被标记为 waiting-for-triage (等待分类)，等待团队成员对其进行分类。在问题被审核后，团队可能会需要您提供提供更多的详细信息，并根据调查结果为问题分配目标里程碑或以特殊的状态关闭。

在修复了这个问题之后，此 issue 将被关闭，但是在修复发布之前可能仍会重新打开。之后，该问题通常将不再重新打开。在极少数情况下，如果问题根本没有解决，问题可能会重新打开。然而，在大多数情况下，任何后续的报告都需要创建具有新描述的新问题。

=== 提交一个 Pull Request

. 你应该先创建一个 issue 吗？不需要，您只需要创建  pull request 通过一些文字描述来提供上下文和动机，就像处理问题一样。如果您想先开始讨论或已经创建了一个问题，一旦创建了  pull request，我们将关闭该问题，并由  pull request 取代，关于该问题的讨论将在 pull request 下继续。
. 始终检查主分支并针对它提交 pull requests （目标版本参见 settings.gradle）。将根据具体情况考虑向后移植到先前版本，并在问题跟踪器中反映为修复版本。
. 有意识地选择提交的粒度，压缩同一逻辑更改的多次编辑或更正的提交。有关简化提交历史的概述，请参阅 https://git-scm.com/book/en/Git-Tools-Rewriting-History[Pro Git] 中 Rewriting History  一节。
. 格式化提交信息，在主题的一行使用 55 个字符，描述每行为 72 个字符，然后是问题修复，例如. Closes gh-22276。 请参阅 https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#Commit-Guidelines[Pro Git] 的 Commit Guidelines 部分，以便在提交消息周围的最佳实践，并使用 `git log` 查看一些示例。
. 如果有之前的问题，请在拉取请求的描述中引用 GitHub 问题编号。
. 如果请求被接受，您的贡献可能会在合并之前根据需要进行大量修改。如果您的大部分更改保持不变，您可能会保留 Git 提交的作者归属。您也可能会被要求重新提交。
. 如果要求进行更正，只需将更改推送到同一分支，您的拉取请求就会更新。换句话说，当被要求进行更改时，您不需要创建新的拉取请求。

=== 参与评论
帮助审查拉取请求是另一种很好的贡献方式。您的反馈有助于塑造新功能的实现。但是，在审查拉取请求时，除非您是 Spring 框架的核心提交者，否则请不要批准或拒绝 PR。

== 构建源码

=== 从源码构建
Jcohy Gradle Plugins 的源码可以使用 Gradle 的命令行构建。我们在项目中包含了 Gradle’s wrapper scripts (./gradlew 或 gradlew.bat)，这样您可以不用下载安装 Gradle 也可以在本地构建。

Jcohy Gradle Plugins 是基于 JDK 1.8 编写的。您应该使用 HotSpot JVM JDK 1.8 或更高的版本构建.

可以使用 Gradle 命令从根目录构建项目：

[indent=0]
----
$ ./gradlew build
----

=== 构建参考文档

项目的参考文档也在此项目中，请参阅 `jcohy-gradle-plugins/src/docs/asciidoc`。我们使用 https://asciidoctor.org/docs/asciidoc-writers-guide/[Asciidoc]，您可以使用以下命令在本地构建文档：

[indent=0]
----
$ ./gradlew asciidoc
----

[NOTE]
====
生成的 HTML , Api Doc 和 PDF 文档在 `jcohy-gradle-plugins/build/docs/` 目录中对应的文件夹中。
====

=== 发布

项目使用了 `io.github.gradle-nexus.publish-plugin` 插件来向中央仓库发布组件。

[NOTE]
====
注意，在 jcohy-java-convention 项目中，在发布组件的时候不要发布生成的插件的 `pom` 文件。您可以执行  `publishMavenJavaPublicationToSonatypeRepository` 任务。或者在执行 `publishToSonatype` 任务是跳过 `publishPluginMavenPublicationToSonatypeRepository` 任务。

[source]
----
$ ./gradlew clean publishMavenJavaPublicationToSonatypeRepository
----

[source]
----
$ ./gradlew clean publishToSonatype -x publishPluginMavenPublicationToSonatypeRepository
----
====

最后，调用 `closeAndReleaseSonatypeStagingRepository` 就可以关闭并发布到中央仓库了。当然，您也可以手动的关闭和发布此组件。 当执行 `publishToSonatype` 任务将项目上传到 sonatype 仓库后，访问 https://oss.sonatype.org/#stagingRepositories[https://oss.sonatype.org/#stagingRepositories] 进行查看。可以手动关闭和发布

=== 使用 IDE

如果您没有 IDE 的偏好，我们会建议您在编写代码时使用 https://spring.io/tools/sts[Spring Tools Suite] 套件 或 https://www.jetbrains.com/idea[IntelliJ IDEA] 或 https://eclipse.org/[Eclipse] 。我们使用 Eclipse 的 https://projects.eclipse.org/projects/tools.buildship[BuildShip] 插件进行 Gradle 支持。 其他的 IDE 和工具也应该可以正常工作。

==== 导入 Eclipse

您可以将 Jcohy Gradle Plugins 代码导入任何基于 Eclipse 2021-03 的发行版。

===== 安装 Eclipse

===== 手动安装 Buildship 插件

如果你更喜欢自动手动安装 Eclipse，你可以使用 Eclipse https://projects.eclipse.org/projects/tools.buildship[Buildship] 插件。
如果你还没有安装 Buildship，您可以从 "`Eclipse marketplace`" 获取此插件。

===== 安装 Spring Formatter 插件

* 选择 "`Help`" -> "`Install New Software`".
* 添加 `https://repo.spring.io/javaformat-eclipse-update-site/` 网址.
* 安装 "Spring Java Format".

NOTE: 此插件是可选的.
即使没有此插件也能导入项目，但是您的的代码更改不会自动格式化。

安装了插件后，您可以从  `File -> Import...` 菜单选择 `Gradle -> Existing Gradle project` 来导入代码。

==== 导入 IntelliJ IDEA

如果您已经执行了 checkout 了此存储库，请使用 "`File`" -> "`Open`" ，然后选择根目录的 `build.gradle` 文件来导入代码。

或者，您可以使用 IntelliJ IDEA 来 checkout 代码。使用  "`File`" -> "`New`" -> "`Project from Version Control`"  ，URL 为 https://github.com/jcohy/jcohy-gradle-plugins.git[https://github.com/jcohy/jcohy-gradle-plugins.git]。 检出完成后，会弹出一个窗口，建议打开项目。

===== 安装 Spring Formatter 插件

如果您还没有这样做，请安装格式化程序插件，以便在 IDE 中重新格式化代码时自动应用正确的格式化规则。

* 下载最新的 https://search.maven.org/search?q=g:io.spring.javaformat%20AND%20a:spring-javaformat-intellij-idea-plugin[IntelliJ IDEA plugin].
* 选择 "`IntelliJ IDEA`" -> "`Preferences`".
* 选择 "`Plugins`".
* 选择 "`Install Plugin from Disk...`".
* 选择你已经下载好的 jar 包.

===== 导入额外的代码样式

格式化程序并未涵盖所有规则，有时候您需要添加一个额外的文件。

* 选择 "`IntelliJ IDEA`" -> "`Preferences`".
* 选择 "`Editor`" -> "`Code Style`".
* 选择 "`Import Scheme`" -> "`IntelliJ IDEA code style XML`".
* 选择本仓库的 `idea/codeStyleConfig.xml` .

==== 从其他 IDE 导入

大多数 Java IDE 都很好地支持 Gradle。请参阅相关的 IDE 文档。

=== 在 Windows 上克隆 git 仓库

git 存储库中的某些文件可能会超过 Windows 最大文件路径(260 个字符)，具体取决于您克隆存储库的位置。如果你收到 `Filename too long` 错误，设置 `core.longPaths=true` git 选项":

[source,shell]
----
git clone -c core.longPaths=true https://github.com/jcohy/jcohy-gradle-plugins.git
----