name: Publish To Maven Center

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
      - name: Build with Gradle
        run: ./gradlew build
      - name: Decode Gpg
        run: |
          echo "${{secrets.SIGNING_SECRET_KEY_RING_FILE}}" > ~/.gradle/secring.gpg.b64 base64-d~/.gradle/secring.gpg.b64>~/.gradle/secring.gpg
      - name: Publish To Maven Center
        run: ./gradlew clean publishToSonatype -x publishPluginMavenPublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository
        env:
          NEXUS_USERNAME: ${{secrets.NEXUS_USERNAME}}
          NEXUS_PASSWORD: ${{secrets.NEXUS_PASSWORD}}
          SIGNING_KEYID: ${{secrets.SIGNING_KEYID}}
          SIGNING_PASSWORD: ${{secrets.SIGNING_PASSWORD}}
          SIGNING_SECRETKEYRINGFILE: ~/.gradle/secring.gpg