name: Publish To Maven Center

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Cache Gradle Package
        uses: actions/cache@v4.0.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Decode Gpg
        run: |
          echo "${{secrets.SIGNING_SECRETKEYRINGFILE}}" > secring.gpg.b64
          base64 -d secring.gpg.b64 > secring.gpg
      - name: Publish To Maven Center
        run: ./gradlew clean publishToSonatype -x publishPluginMavenPublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository -x test -Psigning.keyId=${{secrets.SIGNING_KEYID}} -Psigning.password=${{secrets.SIGNING_PASSWORD}} -Psigning.secretKeyRingFile=$(echo secring.gpg)
        env:
          NEXUS_USERNAME: ${{secrets.NEXUS_USERNAME}}
          NEXUS_PASSWORD: ${{secrets.NEXUS_PASSWORD}}
          SIGNING_KEYID: ${{secrets.SIGNING_KEYID}}
          SIGNING_PASSWORD: ${{secrets.SIGNING_PASSWORD}}
          SIGNING_SECRETKEYRINGFILE: $(echo secring.gpg)
